# Generated by Django 4.2.4 on 2024-04-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("author", models.CharField(max_length=200, verbose_name="Автор")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Цена")),
                ("read", models.BooleanField(default=False, verbose_name="Прочтено")),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
